backend:
  name: github
  repo: MikeSchneke/Atemstark-Site
  branch: main
  auth_type: implicit
  app_id: Ov23liuJvdVjUw4h9bSr

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage (DE)"
        name: "index_de"
        file: "index.html"
        editor:
          preview: false
        fields:
          - { label: "HTML", name: "body", widget: "code", default_language: "html" }

      - label: "Homepage (EN)"
        name: "index_en"
        file: "en/index.html"
        editor:
          preview: false
        fields:
          - { label: "HTML", name: "body", widget: "code", default_language: "html" }
